In [ ]:
def mul_mat(a, b, c, i, ii, j, jj):
  if i == ii: #i=indice inicial, ii:indice final:len
    temp = 0
    for k in range(len(a)):
      temp += a[i][k] * b[k][j]
    c[i][j] = temp
  else:
    imid = (i + ii) // 2
    jmid = (j + jj) // 2
    mul_mat(a, b, c,        i, imid,        j, jmid)
    mul_mat(a, b, c, imid + 1,   ii,        j, jmid)
    mul_mat(a, b, c,        i, imid, jmid + 1, jj)
    mul_mat(a, b, c, imid + 1,   ii, jmid + 1, jj)


In [ ]:
import numpy as np

def main():
  a = np.random.randint(10, size=(8, 8))  #Genera valores [0,9] en una matriz de 8*8
  b = np.random.randint(10, size=(8, 8))  #Genera valores [0,9] en una matriz de 8*8
  print("Matriz A: "); print(a)
  print("Matriz B: "); print(b)
  c = np.zeros((8, 8))  #Retorna una Matriz de 8*8 rellena de ceros
  mul_mat(a, b, c, 0, len(a) - 1, 0, len(a) - 1)  #len(matriz) retorna el tamaño de la dimension, 8 en este caso
  assert (c == np.matmul(a, b)).all()
  print("\nMatriz C = A x B: ")
  print(c)

main()

Matriz A: 
[[3 6 6 8 3 7 7 3]
 [9 5 0 1 4 7 3 7]
 [7 3 6 6 8 3 7 2]
 [8 5 5 1 8 5 8 2]
 [9 1 2 8 5 3 1 6]
 [7 6 1 4 1 6 8 9]
 [0 6 0 6 8 9 1 4]
 [3 4 2 6 5 8 2 2]]
Len A:  8
Matriz B: 
[[4 6 3 6 1 8 8 9]
 [6 0 4 9 1 6 8 7]
 [3 0 9 3 5 5 7 6]
 [4 9 7 3 7 9 9 2]
 [3 6 8 5 2 0 9 6]
 [5 6 1 4 3 8 4 7]
 [0 8 1 1 0 6 4 6]
 [3 0 2 9 5 0 8 6]]

Matriz C = A x B: 
[[151. 206. 187. 191. 137. 260. 293. 248.]
 [138. 153. 110. 216.  85. 185. 253. 251.]
 [133. 218. 207. 182. 117. 224. 304. 255.]
 [136. 199. 177. 197.  86. 216. 288. 282.]
 [128. 182. 161. 185. 125. 190. 275. 209.]
 [143. 184. 122. 229. 111. 229. 284. 269.]
 [141. 164. 148. 185. 111. 168. 246. 195.]
 [127. 166. 139. 155. 103. 188. 225. 189.]]
